import Foundation
import AppKit

public struct SessionReply: Codable {
    public var id: String
    public var running: Bool?
    public var runTime: Double?
    public var error: String?
    public init(id: String, running: Bool? = nil, runTime: Double? = nil, error: String? = nil) {
        self.id = id; self.running = running; self.runTime = runTime; self.error = error
    }
}
public struct CaptureState {
    public private(set) var running: Bool?
    public private(set) var busy = false
    public private(set) var error: String?
    public init() {}
    public mutating func begin(_ action: String) -> Bool {
        guard !busy else { return false }
        if action != "status" {
            guard let running, (action == "start" && !running) || (action == "stop" && running) else { return false }
        }
        busy = true; return true
    }
    public mutating func accept(_ reply: SessionReply) { busy = false; error = reply.error; running = reply.error == nil ? reply.running : nil }
    public mutating func fail(_ message: String) { busy = false; running = nil; error = message }
}
public final class AudioHijackBridge {
    public let paths: Paths
    public let executable: String
    public init(paths: Paths, executable: String) { self.paths = paths; self.executable = executable }
    public static func literal(_ value: String) -> String {
        String(data: try! JSONEncoder().encode(value), encoding: .utf8)!
    }
    public func script(action: String, id: String, expires: Double) -> String {
        let helper = Self.literal(executable)
        return """
        // Generated by Recordi. Uses Audio Hijack's documented JavaScript API.
        (function () {
          var result = {id: \(Self.literal(id))};
          try {
            if (Date.now() > \(Int64(expires * 1000))) throw new Error("Recordi command expired; no action taken.");
            app.autoRestoreWindows = false;
            app.autoOpenWindows = false;
            var sessions = app.sessions.filter(function (s) { return s.name === "Meeting Recorder"; });
            if (sessions.length !== 1) throw new Error("Expected exactly one session named Meeting Recorder; found " + sessions.length + ".");
            var session = sessions[0];
            var action = \(Self.literal(action));
            if (action === "start" && !session.running) session.start();
            if (action === "stop" && session.running) session.stop();
            result.running = session.running;
            result.runTime = session.runTime;
          } catch (e) { result.error = String(e); }
          var response = app.runShellCommand(app.shellEscapeArgument(\(helper)) + " --reply " + app.shellEscapeArgument(JSON.stringify(result)));
          if (response[0] !== 0) console.error("Recordi could not save command response: " + response[2]);
        })();
        """
    }
    public func completionScript() -> String {
        """
        // #needsFile
        // Attach to Meeting Recorder > Scripting > Recording Stop.
        if (event.eventType === "fileDidEnd" && event.session.name === "Meeting Recorder") {
          var cmd = app.shellEscapeArgument(\(Self.literal(executable))) + " --enqueue " + app.shellEscapeArgument(event.file.filePath);
          // The helper only persists a job. Fully detach its standard streams; never run Whisper here.
          app.runShellCommand("/usr/bin/nohup " + cmd + " </dev/null >/dev/null 2>&1 &");
        }
        """
    }
    public func installScripts() throws {
        try Data(completionScript().utf8).write(to: paths.commands.appendingPathComponent("Transcribe Finished Recording.js"), options: .atomic)
        for action in ["start", "stop", "status"] {
            // These convenience commands are also safe to open manually. App commands use expiring UUID requests.
            try Data(script(action: action, id: UUID().uuidString, expires: 4102444800).utf8)
                .write(to: paths.commands.appendingPathComponent(action + ".ahcommand"), options: .atomic)
        }
    }
    public func perform(_ action: String, audioHijack: String, timeout: TimeInterval = 8,
                        isRunning: (() -> Bool)? = nil,
                        invoke: ((URL) throws -> Void)? = nil) throws -> SessionReply {
        guard ["start", "stop", "status"].contains(action) else { throw RecordiError("Unknown command.") }
        guard fm.fileExists(atPath: audioHijack) else { throw RecordiError("Audio Hijack is missing. Rerun install.sh after installing it.") }
        let id = UUID().uuidString
        // Passive checks must not launch the recording app after the user quits it.
        // Resolve the configured bundle so this also works if Audio Hijack is moved.
        if action != "start" {
            let running = isRunning?() ?? Bundle(path: audioHijack)?.bundleIdentifier.map {
                NSRunningApplication.runningApplications(withBundleIdentifier: $0).contains { !$0.isTerminated }
            } ?? false
            if !running { return SessionReply(id: id, running: false, runTime: 0) }
        }
        let command = paths.commands.appendingPathComponent("request-" + id + ".ahcommand")
        let response = paths.state.appendingPathComponent("reply-" + id + ".json")
        defer { try? fm.removeItem(at: command); try? fm.removeItem(at: response) }
        try Data(script(action: action, id: id, expires: Date().timeIntervalSince1970 + timeout).utf8).write(to: command, options: .atomic)
        if let invoke { try invoke(command) }
        else { _ = try ProcessRunner().capture("/usr/bin/open", ["-g", "-a", audioHijack, command.path], timeout: 5) }
        let deadline = Date().addingTimeInterval(timeout)
        while Date() < deadline {
            if let reply = try? readJSON(SessionReply.self, response), reply.id == id {
                if let error = reply.error { throw RecordiError(error) }
                guard reply.running != nil else { throw RecordiError("Audio Hijack returned no recording state.") }
                // A transition may take a moment; callers re-query actual state, never blindly retry a mutation.
                return reply
            }
            Thread.sleep(forTimeInterval: 0.05)
        }
        throw RecordiError("Audio Hijack did not respond. Enable Settings → Advanced → Allow execution of external scripts. State will be checked again.")
    }
    public func saveReply(_ json: String) throws {
        let reply = try JSONDecoder().decode(SessionReply.self, from: Data(json.utf8))
        guard UUID(uuidString: reply.id) != nil else { throw RecordiError("Invalid response identifier.") }
        try atomic(reply, to: paths.state.appendingPathComponent("reply-" + reply.id + ".json"))
    }
}
